server:
  port: 10086 # 服务端口
spring:
  application:
    name: eurekaserver
  cloud:
    inetutils: preferred-networks:192.168.0 #服务注册时优先使用这个网段。
eureka:
  client:
    service-url: # eureka的地址信息
      defaultZone: http://127.0.0.1:10086/eureka
